### PR TITLE
Fix parsing of package id

### PR DESCRIPTION
**Pull request by septatrix**
Previously the order id was extracted which does not match the cID

### CODE REVIEW

**Comment by Buxdehuda** [comment]
This one fails all the previously provided test cases. I honestly don't know if they are still used, but backwards compatability is always nice to have since the page seems to differ greatly depending on the products you bought

**Comment by initB10r** [comment]
This fix worked wonderfully for me. A renew was not possible without it.

**Comment by Buxdehuda** [comment]
@chrstn-hntschl As you we're the last person to provide an example for the package id parsing, can you confirm this change works for you?

**Comment by chrstn-hntschl** [comment]
@Buxdehuda Can confirm it works! Thanks a lot for all your efforts !

**Comment by Buxdehuda** [comment]
Good to hear. I deleted the old tests, it probably doesn't make that much sense to check something that changes frequently.
Maybe in the future we could save the successfully parsed cID in a file on a per-domain basis, so that for existing users the script won't break that easily.

Anyway, thanks for adapting the code to reflect the current state of the Strato website design.

**Pull request merged**
